# config/config.yaml
logging:
  level: INFO
  file: logs/trading.log

security:
  key_file: config/key.key
  credentials_file: config/credentials.enc

strategy:
  symbols_file: config/symbol_list.json
  risk_params_file: config/risk_params.json
  timeframes: [ 1, 5, 15 ]
  bars: 500
